name: user_profile_gatekeeper
description: "Ensure that your users have provided necessary profile information before they can access your app."
version: 1.0.0
repository: https://github.com/Jake-Mok-Nelson/user_profile_gatekeeper

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
