name: Test Coverage > 70%

on:
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
            flutter-version: 3.24.0
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests with coverage
        run: flutter test --coverage
      - name: Check coverage
        shell: bash
        run: |
          set -e
          COVERAGE=$(perl -nle 'print $1 if /lines\.*: (\d+\.\d+)%/' coverage/lcov.info)
          if (( $(echo "$COVERAGE < 70" | bc -l) )); then
            echo "Code coverage is $COVERAGE%, which is below required 70%"
            exit 1
          fi
