# Flutter CI Workflow
# This workflow runs Flutter tests and builds for multiple platforms on pull requests to main branch
#
# Runs on:
# - Ubuntu Latest: Builds Linux, Web and Android APK
# - Windows Latest: Builds Windows executable
# - macOS Latest: Builds macOS and iOS apps
#
# Steps:
# 1. Checks out repository
# 2. Sets up Flutter environment
# 3. Gets dependencies using 'flutter pub get'
# 4. Runs Flutter tests
# 5. Performs platform-specific builds
#
# Note: Matrix strategy ensures tests and builds run on all specified operating systems
name: Flutter CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.x
      - run: flutter pub get
      - run: flutter test
      - name: build
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            flutter build windows
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            flutter build macos
            flutter build ios
          elif [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            flutter build linux
            flutter build web
            flutter build apk
          fi
